### PR TITLE
Make Cache Configurable

### PR DESCRIPTION
**Pull request by onairmarc**
This PR introduces two new config values. `cache.prefix` and `cache.ttl`.

The prefix defaults to `filament_kb_`. So if your Laravel App's cache prefix is `laravel_', the cache key would look like `laravel_filament_kb_XXXXX`.

The `cache.ttl` value defaults to `86400` (1 day). This way, you do not need to clear your entire cache for documentation to begin updating.

### CODE REVIEW

**Comment by lukas-frey** [comment]
Hi, thanks for the PR. What do you mean by clearing the entire cache when updating?

You are not supposed to clear the cache. And whenever you do changes to the documentation, the hash changes and the documentation is cached again. There's no need to remove it from the cache as it's pretty much a static page - it gets a huge performance boost when it's cached, especially when using Syntax highlighting, which can take a few seconds to load.

**Comment by onairmarc** [comment]
The [documentation](https://github.com/GuavaCZ/filament-knowledge-base?tab=readme-ov-file#cache) states that the cache should be cleared if changes don't appear. In my testing, changes were not appearing even when the underlying content did change and I needed to add the `app:cache` clear command to my deploy steps.

This PR was aimed at fixing that issue. I could change it to where if `cache.ttl = 'forever'` the cache forever behavior is used, but if `cache.tll = {any number}`, then the cache remember behavior is used.

One problem for some may be that the current cache methodology only adds to the cache when content changes but doesn't appear to remove the old cache keys. By setting them to expire at defined intervals, the cache won't grow unnecessarily. This is a mid-level issue for me. There are things I care about more, and there are things I care about less regarding the number of stale items in the cache.

Please let me know what you think, and I'd be happy to make the appropriate adjustments.

**Comment by lukas-frey** [comment]
Since I can't reproduce the issue, it would be nice if you could provide a repo, where the cache doesn't work, as that needs to be fixed then.

But if you keep the way it is now the default (i.e. 'forever' will be the default), I have no problem with merging the PR. 👍

**Comment by onairmarc** [comment]
I'll get on that now. Should have updates pushed within the hour

**Comment by onairmarc** [comment]
Changes applied. The default is now cache forever with the option to specify an integer greater than 0 as the ttl. If an interger less than 1 or a string other than forever is supplied, an `InvalidArgumentException` is thrown with the message `The cache.ttl configuration must be an integer greater than 0 or the string "forever".`

**Pull request merged**
